#!/bin/sh

# This does not handle creating the Windows Free42.ico. Windows ico is a multi-
# resolution format, and I don't know how to deal with that.
# I used https://icoconvert.com/, and that seems to work fine, including
# handling transparency.
# 
# Rounded corner images created using https://pinetools.com/round-corners-image
# with a radius of 344 (based on a 5:32 corner-radius:size ratio).
# The rounded corner icons are only used for the desktop versions.
# 
# Android icons now generated by Image Asset Studio
# from the android-* icons in this directory
# 48:android/app/src/main/res/drawable-mdpi/icon.png
# 72:android/app/src/main/res/drawable-hdpi/icon.png
# 96:android/app/src/main/res/drawable-xhdpi/icon.png
# 144:android/app/src/main/res/drawable-xxhdpi/icon.png
# 192:android/app/src/main/res/drawable-xxxhdpi/icon.png
#
# Note: The Mac icons look a bit large, compared to most other apps' icons.
# They are maximum size, which is not unheard of (other examples of apps with
# maximally large icons on my computer are Kindle Classic, Mathematica, and
# FileZilla), but most Mac apps appear to limit their icons to 13/16 of the
# available width and height. Just so you know.

if [ $1 == "free42" ]
then
    ROUNDED=icon-2200x2200-lighter-rounded.png
    IOS_ANY=icon-2200x2200-lighter.png
    IOS_DARK=icon-2200x2200-lighter-dark-mode.png
    IOS_TINTED=icon-2200x2200-lighter-tinted-mode.png
    NAME=Free42
    SRC_DIR=$HOME/free42
elif [ $1 == "plus42" ]
then
    ROUNDED=icon-orange-2200x2200-lighter-rounded.png
    IOS_ANY=icon-orange-2200x2200-lighter.png
    IOS_DARK=icon-orange-2200x2200-lighter-dark-mode.png
    IOS_TINTED=icon-orange-2200x2200-lighter-tinted-mode.png
    NAME=Plus42
    SRC_DIR=$HOME/plus42
else
    echo "Usage: convert.sh [ free42 | plus42 ]"
    exit 1
fi

SQUARELIST=(
120:iphone/icon.png
1024:iphone/$NAME/Images.xcassets/AppIcon.appiconset/any.png
)

ROUNDLIST=(
57:iphone/about-icon.png
64:iphone/simpleserver/site-icon.png
114:iphone/about-icon@2x.png
16:mac/icon.iconset/icon_16x16.png
32:mac/icon.iconset/icon_16x16@2x.png
32:mac/icon.iconset/icon_32x32.png
64:mac/icon.iconset/icon_32x32@2x.png
128:mac/icon.iconset/icon_128x128.png
256:mac/icon.iconset/icon_128x128@2x.png
256:mac/icon.iconset/icon_256x256.png
512:mac/icon.iconset/icon_256x256@2x.png
512:mac/icon.iconset/icon_512x512.png
1024:mac/icon.iconset/icon_512x512@2x.png
)

XPMLIST=(
48:gtk/icon-48x48.xpm
128:gtk/icon-128x128.xpm
)

for TARGET in ${SQUARELIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopam "$IOS_ANY" | pamscale -xysize $RES $RES | pamtopng > $SRC_DIR/$IMG
done

pngtopam "$IOS_DARK" | pamscale -xysize 1024 1024 | pamtopng > $SRC_DIR/iphone/$NAME/Images.xcassets/AppIcon.appiconset/dark.png
pngtopam "$IOS_TINTED" | pamscale -xysize 1024 1024 | pamtopng > $SRC_DIR/iphone/$NAME/Images.xcassets/AppIcon.appiconset/tinted.png

for TARGET in ${ROUNDLIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopam -alphapam "$ROUNDED" | pamscale -xysize $RES $RES | pamtopng > $SRC_DIR/$IMG
done

for TARGET in ${XPMLIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopnm "$ROUNDED" | pnmscale -xysize $RES $RES > icon_${RES}_xpm
    pngtopnm -alpha "$ROUNDED" | pnmscale -xysize $RES $RES > icon_${RES}_mask
    ppmtoxpm -alphamask=icon_${RES}_mask icon_${RES}_xpm > $SRC_DIR/$IMG
done

rm -f icon_*_xpm icon_*_mask
