#!/bin/sh

# This does not handle creating the Windows Free42.ico.
# That is a multi-resolution format, don't know how to deal with that.
# I used https://icoconvert.com/, and that seems to work fine, including
# handling transparency.
# Rounded corner images created using https://pinetools.com/round-corners-image
# with a radius of 344 (based on a 5:32 corner-radius:size ratio).
# The rounded corner icons are only used for the desktop versions.
# 
# Files used to generate the latest icons:
# icon-2200x2200-lighter.png
# icon-2200x2200-lighter-rounded.png
# icon-2200x2200-lighter-dark-mode.png
# icon-2200x2200-lighter-tinted-mode.png
# icon-orange-2200x2200-lighter.png
# icon-orange-2200x2200-lighter-rounded.png
# icon-orange-2200x2200-lighter-dark-mode.png
# icon-orange-2200x2200-lighter-tinted-mode.png

OPAQUE="$1"
TRANSPARENT="$2"

echo "Opaque original: $OPAQUE"
echo "Transparent original: $TRANSPARENT"

OPAQUELIST=(
#120:iphone/icon.png
#1024:iphone/Free42/Images.xcassets/AppIcon.appiconset/any.png
)

TRANSPARENTLIST=(
57:iphone/about-icon.png
114:iphone/about-icon@2x.png
64:iphone/simpleserver/site-icon.png
64:mac/icon.iconset/icon_32x32@2x.png
128:mac/icon.iconset/icon_128x128.png
512:mac/icon.iconset/icon_256x256@2x.png
32:mac/icon.iconset/icon_32x32.png
512:mac/icon.iconset/icon_512x512.png
16:mac/icon.iconset/icon_16x16.png
32:mac/icon.iconset/icon_16x16@2x.png
256:mac/icon.iconset/icon_128x128@2x.png
1024:mac/icon.iconset/icon_512x512@2x.png
256:mac/icon.iconset/icon_256x256.png
)

XPMLIST=(
48:gtk/icon-48x48.xpm
128:gtk/icon-128x128.xpm
)

# Android icons now generated by Image Asset Studio
# from the android-* icons in this directory
# 96:android/app/src/main/res/drawable-xhdpi/icon.png
# 144:android/app/src/main/res/drawable-xxhdpi/icon.png
# 72:android/app/src/main/res/drawable-hdpi/icon.png
# 48:android/app/src/main/res/drawable-mdpi/icon.png
# 192:android/app/src/main/res/drawable-xxxhdpi/icon.png

for TARGET in ${OPAQUELIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopam "$OPAQUE" | pamscale -xysize $RES $RES | pamtopng > $IMG
done

for TARGET in ${TRANSPARENTLIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopam -alphapam "$TRANSPARENT" | pamscale -xysize $RES $RES | pamtopng > $IMG
done

for TARGET in ${XPMLIST[@]}
do
    RES=`echo $TARGET | sed 's/^\(.*\):.*$/\1/'`
    IMG=`echo $TARGET | sed 's/^.*:\(.*\)$/\1/'`
    pngtopnm "$TRANSPARENT" | pnmscale -xysize $RES $RES > icon_${RES}_xpm
    pngtopnm -alpha "$TRANSPARENT" | pnmscale -xysize $RES $RES > icon_${RES}_mask
    ppmtoxpm -alphamask=icon_${RES}_mask icon_${RES}_xpm > $IMG
done

rm -f icon_*_xpm icon_*_mask
